
package com.example.service.wsdl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "StudentServicePortType", targetNamespace = "http://example.com/student")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface StudentServicePortType {


    /**
     * 
     * @param parameters
     * @return
     *     returns com.example.service.wsdl.AttendanceResponse
     */
    @WebMethod(action = "http://example.com/student/studentAttendance")
    @WebResult(name = "AttendanceResponse", targetNamespace = "http://example.com/student", partName = "parameters")
    public AttendanceResponse studentAttendance(
        @WebParam(name = "AttendanceRequest", targetNamespace = "http://example.com/student", partName = "parameters")
        AttendanceRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.example.service.wsdl.StudentInfoRecordResponse
     */
    @WebMethod(action = "http://example.com/student/recordStudentInfo")
    @WebResult(name = "StudentInfoRecordResponse", targetNamespace = "http://example.com/student", partName = "parameters")
    public StudentInfoRecordResponse recordStudentInfo(
        @WebParam(name = "StudentInfoRecordRequest", targetNamespace = "http://example.com/student", partName = "parameters")
        StudentInfoRecordRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.example.service.wsdl.StudentInfoQueryResponse
     */
    @WebMethod(action = "http://example.com/student/queryStudentInfo")
    @WebResult(name = "StudentInfoQueryResponse", targetNamespace = "http://example.com/student", partName = "parameters")
    public StudentInfoQueryResponse queryStudentInfo(
        @WebParam(name = "StudentInfoQueryRequest", targetNamespace = "http://example.com/student", partName = "parameters")
        StudentInfoQueryRequest parameters);

}
